### ISSUE TITLE
api测试如何？

### ISSUE THREAD

**Issue by logbird** [geektown/raspberry-xunfei#1]
我最近也在研究讯飞api在树莓派上的应用。板子还没到货，麻烦问下，讯飞提供的sdk是否支持调用声卡录音并且进行端点检查这些操作呢？我看文档貌似是支持的，但是我看他给的sdk都是指定语音文件的。。。

**Comment by geektown** [comment]
我使用的就是wav文件和文本的转化。调用声卡录音是pyaudio代码来做的。不是用的讯飞sdk。

**Comment by logbird** [comment]
是的 我今天又看了下文档 大概明白他那个意思了 他是在write的时候进行的端点检查
